version: "3.8"

services:
  backend:
    image: rms:latest
    networks:
      rms-network:
    ports:
      - "8069:8000"
    env_file:
      - .env
    volumes:
      - "./rms:/home/app/rms"
      - "./pyproject.toml:/home/app/pyproject.toml"
      - "./poetry.lock:/home/app/poetry.lock"

  db:
    image: postgres:15
    networks:
      rms-network:
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    volumes:
      - minio-data:/mnt/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      rms-network:


volumes:
  pgdata:
  minio-data:


networks:
  rms-network: