version: "3.8"

services:
  backend:
    image: rms:latest
    ports:
      - "8069:8000"
    env_file:
      - .env
    volumes:
      - "./rms:/home/app/rms"
      - "./pyproject.toml:/home/app/pyproject.toml"
      - "./poetry.lock:/home/app/poetry.lock"

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: