name: Frontend branch push

on:
  push:
    branches:
      - "**"
    paths:
      - 'rms_fe/**'

jobs:
  lint_and_test_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        working-directory: ./rms_fe
        run: npm install

      - name: Lint
        working-directory: ./rms_fe
        run: npm run lint

#      - name: Test
#        working-directory: ./rms_fe
#        run: npm run test

      - name: Build
        working-directory: ./rms_fe
        run: npm run build