name: Frontend deployment

on:
  push:
    branches:
      - main
    paths:
      - 'rms_fe/**'
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies, build, and test
        working-directory: ./rms_fe
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: rms_fe
          path: ./rms_fe/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - name: Checkout code
        uses: actions/checkout@master

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy App Service and Web App
        id: deploy_webapp
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ vars.AZURE_RG }}
          template: ./.github/workflows/frontend-appservice-template.json
          parameters: appServicePlanName=${{ vars.AZURE_APP_SERVICEPLAN_NAME_FE}} webAppName=${{ vars.AZURE_WEBAPP_NAME_FE}}

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: rms_fe

      - name: Get WebApp/FunctionApp publish profile
        id: get_publishing_profile
        uses: aliencube/publish-profile-actions@v1
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          resourceGroupName: ${{ vars.AZURE_RG }}
          appName: ${{ vars.AZURE_WEBAPP_NAME_FE}}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME_FE}}
          slot-name: 'Production'
          publish-profile: ${{ steps.get_publishing_profile.outputs.profile }}
          package: .